require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe SubmissionsController do
  # This should return the minimal set of attributes required to create a valid
  # Submission. As you add validations to Submission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      html:                '<a href="https://aaronparecki.com" class="h-card">@aaronpk</a>',
      base_url:            'https://aaronparecki.com',
      save_html:           true,
      render_html_in_page: true
    }
  end

  let(:invalid_attributes) do
    {
      html:     nil,
      base_url: nil
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubmissionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'redirects to root' do
      Submission.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to redirect_to root_path
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      submission = Submission.create! valid_attributes
      get :show, params: { id: submission.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session

      # binding.irb

      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'redirects to root' do
      submission = Submission.create! valid_attributes
      get :edit, params: { id: submission.to_param }, session: valid_session
      expect(response).to redirect_to root_path
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Submission' do
        expect do
          post :create, params: { submission: valid_attributes }, session: valid_session
        end.to change(Submission, :count).by 1
      end

      it 'redirects to the created submission' do
        post :create, params: { submission: valid_attributes }, session: valid_session
        expect(response).to redirect_to Submission.last
      end
    end

    context 'with invalid params' do
      it 'renders the show template when save_html is false' do
        invalid_attrs_without_save_html = invalid_attributes.merge(save_html: false)
        post :create, params: { submission: invalid_attrs_without_save_html }, session: valid_session
        expect(response).to be_successful
        expect(response).to render_template :show
      end

      it 'redirects to submission when save_html is true (no model validations exist)' do
        invalid_attrs_with_save_html = invalid_attributes.merge(save_html: true)
        post :create, params: { submission: invalid_attrs_with_save_html }, session: valid_session
        expect(response).to redirect_to Submission.last
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      it 'redirects to root without updating' do
        submission = Submission.create! valid_attributes
        put :update, params: { id: submission.to_param, submission: valid_attributes }, session: valid_session
        expect(response).to redirect_to root_path
      end

      it 'redirects to the submission' do
        submission = Submission.create! valid_attributes
        put :update, params: { id: submission.to_param, submission: valid_attributes }, session: valid_session
        expect(response).to redirect_to root_path
      end
    end

    context 'with invalid params' do
      it 'redirects to root' do
        submission = Submission.create! valid_attributes
        put :update, params: { id: submission.to_param, submission: {} }, session: valid_session
        expect(response).to redirect_to root_path
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'redirects to root without destroying' do
      submission = Submission.create! valid_attributes
      expect do
        delete :destroy, params: { id: submission.to_param }, session: valid_session
      end.not_to change(Submission, :count)
      expect(response).to redirect_to root_path
    end
  end
end
